services:

  db:
    container_name: drinkshop_sql_prod
    image: ${MSSQL_IMAGE}
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data_prod:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    logging: &default_logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - drinkshop_network_prod
  drinkshop-api:
    image: hoangnhat2003/drinkshop-api:${IMAGE_TAG} 
    restart: always


  # 2. Storage - Mở cổng 9000 để Client lấy ảnh
  minio:
    container_name: drinkshop_minio_prod
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data_prod:/data
    logging:
      <<: *default_logging
    networks:
      - drinkshop_network_prod

  # 3. Web API - Chạy song song 2 bản để Load Balancing
  api_1: &api_prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - MinIO__Endpoint=${MINIO_ENDPOINT}
      - MinIO__AccessKey=${MINIO_ROOT_USER}
      - MinIO__SecretKey=${MINIO_ROOT_PASSWORD}
      - MinIO__Bucket=${MINIO_BUCKET}
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      db:
        condition: service_healthy
    logging:
      <<: *default_logging
    networks:
      - drinkshop_network_prod

  api_2:
    <<: *api_prod
    container_name: drinkshop_api_2_prod

  # 4. Gateway - Nginx điều phối traffic
  nginx:
    container_name: drinkshop_nginx_prod
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Cho SSL thật
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    logging:
      <<: *default_logging
    depends_on:
      - api_1
      - api_2
    networks:
      - drinkshop_network_prod

networks:
  drinkshop_network_prod:
    driver: bridge

volumes:
  sql_data_prod:
  minio_data_prod: