name: drinkshop-prod
services:
  db:
    container_name: drinkshop_sql_prod
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - sql_data_prod:/var/opt/mssql
    ports:
      - "1433:1433" # Cổng SQL Prod
    networks:
      - drinkshop_network_prod
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      retries: 5

  minio:
    image: minio/minio
    container_name: drinkshop_minio_prod
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data_prod:/data
    command: server /data --console-address ":9001"
    networks:
      - drinkshop_network_prod

  api_1: &api_base
    container_name: drinkshop_api_1_prod
    image: hoangnhat2003/drinkshop-api:${IMAGE_TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}  # <-- Dòng này phải khớp hoàn toàn với Program.cs
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      db: { condition: service_healthy }
    networks:
      - drinkshop_network_prod

  api_2:
    <<: *api_base
    container_name: drinkshop_api_2_prod

  nginx:
      container_name: drinkshop_nginx_prod
      build: { context: ., dockerfile: Dockerfile_Nginx }
      ports:
        - "80:80"
      depends_on:
        - api_1
        - api_2
      networks:
        - drinkshop_network_prod

networks:
  drinkshop_network_prod:
    driver: bridge

volumes:
  sql_data_prod:
  minio_data_prod: